# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_visibility_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='project author', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(help_text='project group', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='groups.Group', verbose_name='group'),
        ),
    ]
