# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170902_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
