# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20170903_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Admin'), (2, 'Owner')], default=0, verbose_name='access level')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'project collaborator',
            },
        ),
        migrations.AlterField(
            model_name='importedarchive',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_archives', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='importedfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_files', to='projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(help_text='House several projects under the same namespace, just like a folder', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='groups.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text='<strong>Private:</strong> project access must be granted explicitly to each user.<br><strong>Public:</strong> project can be accessed withoutauthentication.', verbose_name='visibility level'),
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborate_projects', through='projects.ProjectCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectcollaborator',
            unique_together=set([('user', 'project')]),
        ),
    ]
