# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170917_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, verbose_name='visibility level'),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Admin'), (2, 'Owner')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborators', to='projects.Project'),
        ),
    ]
