# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170921_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedarchive',
            name='uploaded_from',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Form'), (1, 'API')], default=0, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='importedarchive',
            name='uploaded_by',
            field=models.ForeignKey(help_text='who uploaded the documentation', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='who uploaded'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='groups.Group', verbose_name='group'),
        ),
    ]
