# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170925_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created'], 'verbose_name': 'project'},
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='groups.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(max_length=255, verbose_name='repository URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='project name must be unique under the selected group', max_length=128, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=('group_id',), verbose_name='slug'),
        ),
    ]
