# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170902_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, verbose_name='visibility level'),
        ),
    ]
