# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_auto_20170903_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Admin'), (2, 'Owner')], default=0, verbose_name='access level')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'group collaborator',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='visibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, help_text='<strong>Private:</strong> project access must be granted explicitly to each user.<br><strong>Public:</strong> project can be accessed withoutauthentication.', verbose_name='visibility level'),
        ),
        migrations.AddField(
            model_name='groupcollaborator',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_collaborators', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='groupcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborate_groups', through='groups.GroupCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupcollaborator',
            unique_together=set([('user', 'group')]),
        ),
    ]
