# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20170917_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='visibility_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0, verbose_name='visibility level'),
        ),
        migrations.AlterField(
            model_name='groupcollaborator',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Admin'), (2, 'Owner')], default=0, verbose_name='role'),
        ),
    ]
