# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.utils
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='project author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(help_text='project organization', on_delete=django.db.models.deletion.CASCADE, to='projects.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(max_length=255, verbose_name='repository URL'),
        ),
        migrations.AlterField(
            model_name='projectarchive',
            name='archive',
            field=models.FileField(help_text='archive with project documentation', upload_to=projects.utils.projects_upload_to, validators=[projects.validators.MimeTypeValidator(allowed_mimetypes=('application/x-gzip',))], verbose_name='archive'),
        ),
        migrations.AlterField(
            model_name='projectarchive',
            name='uploaded_by',
            field=models.ForeignKey(help_text='who uploaded the documentation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='who uploaded'),
        ),
    ]
