# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('path', models.FilePathField(match='.*\\.html$', max_length=255, path='/app/alexandria_docs/alexandria_docs/../../data/staticsites', recursive=True)),
                ('md5', models.CharField(max_length=255, verbose_name='MD5 checksum')),
                ('imported_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='archive')),
            ],
            options={
                'verbose_name': 'imported file',
            },
        ),
        migrations.AlterModelOptions(
            name='importedarchive',
            options={'verbose_name': 'imported archive'},
        ),
        migrations.AlterField(
            model_name='importedarchive',
            name='uploaded_by',
            field=models.ForeignKey(help_text='who uploaded the documentation', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='who uploaded'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='project author', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(help_text='project organization', on_delete=django.db.models.deletion.PROTECT, to='projects.Organization', verbose_name='organization'),
        ),
    ]
